name: Build and upload to PyPI

on:
  workflow_dispatch:

jobs:
  build_and_upload_wheels:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.PYRANGES_PYPI_USER }}
      TWINE_PASSWORD: ${{ secrets.PYRANGES_PYPI_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build sdist and wheel
        run: |
          python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/*

      - name: Validate package metadata
        run: |
          python -m twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYRANGES_PYPI_USER }}
          password: ${{ secrets.PYRANGES_PYPI_PASSWORD }}

