name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        # I am using the pip installed by conda, bad practice but OK in C/I I think
        pip3.12 install pyranges-plot[all]==0.1.0
        pip3.12 install ruff pytest
    - name: Check formatting with ruff
      run: |
         ruff format --check src
    - name: Test with pytest
      run: |
        conda install pytest
        pytest --ignore=examples